### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by st7109** [f-koehler/cpp-perf#1]
In file included from /home/work/cpp-perf/example/basic.cpp:31:0:
/home/work/cpp-perf/include/cpp-perf.hpp:221:13: error: declaration of ‘perf::duration perf::timer::duration() const’ [-fpermissive]
             }
             ^
/home/work/cpp-perf/include/cpp-perf.hpp:53:37: error: changes meaning of ‘duration’ from ‘using duration = std::chrono::_V2::system_clock::duration’ [-fpermissive]
     using duration = clock::duration;
                                     ^
/home/work/cpp-perf/include/cpp-perf.hpp:286:13: error: declaration of ‘perf::duration perf::inline_timer::duration() const’ [-fpermissive]
             }
             ^
/home/work/cpp-perf/include/cpp-perf.hpp:53:37: error: changes meaning of ‘duration’ from ‘using duration = std::chrono::_V2::system_clock::duration’ [-fpermissive]
     using duration = clock::duration;
                                     ^
example/CMakeFiles/basic.dir/build.make:62: recipe for target 'example/CMakeFiles/basic.dir/basic.cpp.o' failed

**Comment by f-koehler** [comment]
Sorry, I only started using and maintaining this library last week and somehow missed your issue. This is a typical case of well-it-works-on-my-machine.

If you are still interested in using this project, you problem should be solved starting with commit 416ce1df2e2964e215c4096c0bb8997eb007174b.

Let me know if you encounter any further problems.
