### ISSUE TITLE
Not thread-safe

### ISSUE THREAD

**Issue by FredM67** [f-koehler/cpp-perf#2]
Good perf library but unfortunately not thread-safe.

If wanted, I can make it thread-safe...

**Comment by f-koehler** [comment]
Cool, that someone is interested in this old project (have not used it for more than 7 years). I might want to use it again as well in a current project of mine so I put some effort in updating it.

I just added support for multiple threads. This also is reflected in the output of inline timers, where the thread id (unfortunately this a long number) is prepended to the output. I made the timer stacks thread-safe as well.

I also added an [example](https://github.com/f-koehler/cpp-perf/blob/main/example/inline_mt.cpp). Please let me know if you have any feedback on this.

**Comment by FredM67** [comment]
Why do we need to change this line (and the other one similar):
static thread_local std::ostream *inline_out_ptr = &std::cout;

Since it's only a pointer/reference to the same stuff... ?!?

BTW, to make things really thread-safe and avoid to get the messages messed up, I think we should put a mutex around operator<<, right? 
Each call to << on cout is thread-safe but chaining these operator could lead to have messages from multiple threads mixed up.

Other way would be to first fill a temporary stringstream as in format_code_position and then output it to cout.

**Comment by FredM67** [comment]
Well, in fact, I think the solution with a temporary stringstream is the ONLY working solution since for sure, the operator << will be called elsewhere and the output will be messed up.
With C++20, the solution would be something like that:
`std::osyncstream(std::cout) << "Hello, " << "World!" << '\n';`

**Comment by f-koehler** [comment]
> Why do we need to change this line (and the other one similar): static thread_local std::ostream *inline_out_ptr = &std::cout;

Of course it would be fine of not declaring this static as `thread_local`, so this change is not strictly necessary. However, this allows to use a different stream per thread, might be useful in some scenarios. I think I saw this once in some library...

**Comment by f-koehler** [comment]
> Well, in fact, I think the solution with a temporary stringstream is the ONLY working solution since for sure, the operator << will be called elsewhere and the output will be messed up. With C++20, the solution would be something like that: `std::osyncstream(std::cout) << "Hello, " << "World!" << '\n';`

I made the suggested change of using a `ostringstream` which should insure that the output from different threads does not get mixed up. Of course the `osyncstream` solution is valid as well, but I do not want to bump the C++ requirement 2020 just for that.

I hope the library now behaves as you expect. Let me know if this is not the case ;)

**Comment by FredM67** [comment]
> I hope the library now behaves as you expect. Let me know if this is not the case ;)

Well in fact, my changes match exactly what you've done... so these changes must be correct :D
Thx

**Comment by f-koehler** [comment]
> > I hope the library now behaves as you expect. Let me know if this is not the case ;)
> 
> Well in fact, my changes match exactly what you've done... so these changes must be correct :D Thx

Great, if two people agree they can't be wrong :D
